# Generated by Django 2.0.7 on 2018-07-26 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180726_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='locatoin',
            new_name='location',
        ),
    ]
